- name: Run a PowerShell command
  hosts: windows
  tasks:
    - name: Executar comando no Windows
      community.windows.psexec:
        hostname: Dell_Tab.cloudmar.local
        connection_username: olam@cloudmar.LOCAL
        connection_password: skol3121
        executable: powershell.exe
        arguments: Write-Host Hello World